### ISSUE TITLE
Hello world extension with serverextension

### ISSUE THREAD

**Issue by fcollonval** [jtpio/jupyterlab-extension-examples#19]
Hey,

Thx for starting this effort. 

Would it be interesting to integrate an example of *hello world* extension using a server extension like that one:
https://github.com/fcollonval/jupyterlab_api_ext

**Comment by jtpio** [comment]
Absolutely!

This would also be a good opportunity to introduce the "discovery metadata": https://jupyterlab.readthedocs.io/en/latest/developer/extension_dev.html#companion-packages

**Comment by echarles** [comment]
Maybe the serving files examples could be recycled/updated to host @fcollonval jupyterlab_api_ext #7.

The discovery metadata would be a great addition to the examples.

@fcollonval cool jupyterlab_api_ext example. I was thinking in our examples to use the new [log console](https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#v1-2-0) instead of asking the use to open his browser developer tool.

**Comment by jtpio** [comment]
@fcollonval I just used your [server extension cookiecutter](https://github.com/fcollonval/cookiecutter-jupyterlab-extension-with-serverextension) to bootstrap a JLab + Server extension and it's really great! 

Do you think it should be detached from the original fork, so it becomes more visible? And maybe also listed in the official JupyterLab documentation.

Commenting here as there doesn't seem to be the issue tab on that fork.

**Comment by fcollonval** [comment]
@jtpio Glad it fits its purpose 🎉 

Great idea! Do you think I should propose it to be hosted in the jupyterlab group?

**Comment by jtpio** [comment]
Since this question comes back regularly (being able to call Python code from a JLab extension), I think it could make sense.

Maybe the frontend part of the cookiecutter should stay in sync with the [TypeScript cookiecutter](https://github.com/jupyterlab/extension-cookiecutter-ts)?
