### ISSUE TITLE
Move Jupyter Widget example out of widget-tracker

### ISSUE THREAD

**Issue by jtpio** [jtpio/jupyterlab-extension-examples#62]
We could move the `jupyter-widgets` example out of the `widget-tracker` folder, since it's more about Jupyter Widgets than about using a `WidgetTracker`.

**Comment by fcollonval** [comment]
You beat me on this one. I have started looking at it this morning. And at the end, it does not bring much as it is the `kernel-output` displaying a ipywidgets instead of a DataFrame.

I would suggest to simply drop it as jupyter widget example should not be in the scope of this repository.

What do you think?

**Comment by jtpio** [comment]
One interesting part about the Jupyter Widget example was the use of the `OutputArea`.

But since it's indeed covered in `kernel-output`, I would say it's fine to drop this example.

We could always add a section about the Jupyter Widgets in the `kernel-output` example later on.

**Comment by echarles** [comment]
Not enough cycles ATM to bring a valid opinion on this. My attention point is that we don't loose cases here. On way to be sure would be to list the features we want to be covered by the example. We then could see if this `ipywidget display` should be covered by any of the current of future example.
